### ISSUE TITLE
Notificatie werkt niet, zeker bij meerdere keren klikken

### ISSUE THREAD

**Issue by LisaKalse** [srnapls/ThaliAppMap#10]
Iedere keer dat je op "Zet notificatie" klikt, zal er een ander getal verschijnen, dan de keer er voor. Tevens weet ik niet of elapsedRealTime wel is wat je wilt hebben, volgens mij wil je een absolute tijd hebben en is dit dat niet. Lees: http://developer.android.com/reference/android/os/SystemClock.html#elapsedRealtime()

**Comment by gitLabor8** [comment]
Fixed
