### ISSUE TITLE
Meer tijdseenheden bij notificaties

### ISSUE THREAD

**Issue by LisaKalse** [srnapls/ThaliAppMap#16]
Er is momenteel alleen de mogelijkheid om aan te geven hoe veel minuten van tevoren je een notificatie wilt krijgen, maar soms is dit niet de meest handige tijdseenheid. Ik raad aan om een dropdown menu te maken met de keuzes minuten, uren en dagen (neem aan dat weken te groot is).

**Comment by srnapls** [comment]
Alleen minuten, uren en dagen?

**Comment by srnapls** [comment]
Als het goed is heb ik dit nu opgelost!

**Comment by LisaKalse** [comment]
deze heb je nog niet gepusht of wel

**Comment by srnapls** [comment]
Jewel, had alleen verkeerde commit-status erbij gezet. Mijn laatste commit moet deze update hebben.
