### ISSUE TITLE
Backpress bij notificatie zorgt er voor dat hij gezet wordt

### ISSUE THREAD

**Issue by LisaKalse** [srnapls/ThaliAppMap#26]
Dit hoeft niet meer aangezien er nu een knop voor is. Nu denkt men dat je gewoon weg kan zonder iets op te slaan door op de terug knop te drukken. Dit kan dus helemaal verwijderd worden.

**Comment by yorickvP** [comment]
Maar stel: je verandert iets in de notificatie instellingen. Moet dit dan niet toegepast worden? Willen we niet juist de knop weg?

**Comment by LisaKalse** [comment]
Nou ik denk dat als je iets aanpast en je wilt het bevestigen, je dan op de knop drukt. Stel je past het aantal minuten aan en je denkt nee laat maar, ik vond mijn oude tijd beter, zou je dat weer opnieuw moeten invoeren.
