### ISSUE TITLE
vanaf notifications kun je alleen naar settings

### ISSUE THREAD

**Issue by yorickvP** [srnapls/ThaliAppMap#3]
Het menu werkt niet (is het een idee om alle klassen te laten inheriten van een klasse die dat menu implementeert)

**Comment by srnapls** [comment]
voorkeur voor waar het nogmeer naar toe moet?

**Comment by LisaKalse** [comment]
denk dat we gewoon een standaard menu willen overal met de keuzes: kalender, eetlijst en settings? (en uitloggen als je ingelogd ben, zou ook mooi zijn als we geen keuze geven naar de activity waar we in zitten?)
