### ISSUE TITLE
HTML-conversion

### ISSUE THREAD

**Issue by LisaKalse** [srnapls/ThaliAppMap#7]
Niet erg mooie event parser, met voornamelijk veel extra spaties en backslashes

**Comment by gitLabor8** [comment]
Dit heeft niets met de parser te maken:
 de parser haalt een lap tekst met HTML-tags binnen (en raar geplaatste spaties)
In de Information klasse wordt deze tekst door een HTML-converter gehaald, die klaarblijkelijk faalt.
Tl,dr: De fout zit bij HTML-converter in de Information klasse
