### ISSUE TITLE
Verwijder de sleep die in de update zit van de kalender

### ISSUE THREAD

**Issue by LisaKalse** [srnapls/ThaliAppMap#9]
De app bevriest 4 seconden lang, waardoor je ook het ladingsicoontje niet meer ziet draaien, dit is echt lelijk.

**Comment by srnapls** [comment]
En wat gebeurd er als we de Sleep eruit halen?

**Comment by LisaKalse** [comment]
Dan wacht hij niet tot alles klaar is, dus krijg je weer een lege lijst events, dus moeten we dit in een apparte thread doen

**Comment by srnapls** [comment]
omg daar heb ik echt geen verstand van :confused:

**Comment by gitLabor8** [comment]
Ik ook niet.
Het is wel mijn pakkie an
Vind iemand het erg als ik nu eerst even wat andere fixes doe, voordat ik me hier weer in vast bijt?
(die vunzige sleep moet er wel echt uit)

**Comment by gitLabor8** [comment]
Dit is trouwens dezelfde issue als die van Yorick
"Parsen op een andere thread"
